#spring.kafka.consumer.bootstrap-servers=127.0.0.1:9092
#spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#
#spring.datasource.url=jdbc:postgresql://0.0.0.0:5432/kafka
#spring.datasource.username=postgres
#spring.datasource.password=password
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.testWhileIdle=true
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create-drop
#
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring:
  datasource:
    password: password
    url: jdbc:postgresql://0.0.0.0:5432/kafka
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
        show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    kafka:
      bootstrap-servers: 127.0.0.1:9092
      consumer:
        auto-offset-reset: latest
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer